### ISSUE TITLE
Is there a way for decode_json to create 1/0 for bool instead of JSON::PP::Boolean ?

### ISSUE THREAD

**Issue by bessarabov** [rurban/Cpanel-JSON-XS#100]
Here is the code:

```
# perl -MData::Dumper -MCpanel::JSON::XS -E 'say Dumper decode_json q({"a":true, "b":true})'
$VAR1 = {
          'a' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
          'b' => $VAR1->{'a'}
        };

```

I need to convert json bool values to 1/0 or (1 and empty string). Is there any way I can do it with Cpanel::JSON::XS?

So my desired result is to get this kind of strucre from `{"a":true, "b":true}`:

```
$VAR1 = {
          'a' => 1,
          'b' => 1,
        };
```

I need to do such convertion because I'm sending some parts of this perl data structure to some other code that does not work well with blessed objects.

I'm expecting this task to have a simple solution, but I can't find out how to do it. Can you please help?

**Comment by Grinnz** [comment]
The blessed objects are equivalent to 1 when used in a boolean, numeric, or string context. It's often simpler to have the code use them as it expects than to coerce them to unblessed scalars.

**Comment by rurban** [comment]
As @Grinnz said. In the Dumper context it surely looks bad to have objects, but this is the best way to seperate booleans from strings or numbers.

In order to get only the numbers 1 or 0 you need to maintain a patch. There's no cfg option.

**Comment by bessarabov** [comment]
I got it. Thank you.
