### ISSUE TITLE
encoding option to force quoting of the numbers

### ISSUE THREAD

**Issue by filimonov** [rurban/Cpanel-JSON-XS#108]
Currently if JSON::XS see that some scalar is stored internally only as number it never quotes that.

But sometimes that quoting is desired, and currently the only workaround is to stringify all scalars before passing structure to JSON::XS. And that is a) another iteration through the data b) require modification/or copy of original data c) slow (in pure perl it can take even more time that converting to JSON).

Some similar questions on StackOverflow
* https://stackoverflow.com/questions/29974529/perl-json-to-treat-all-numbers-as-string
* https://stackoverflow.com/questions/17068764/why-does-the-json-module-quote-some-numbers-but-not-others
* https://stackoverflow.com/questions/35227290/determining-if-a-perl-scalar-is-a-string-or-integer
etc.

v1 of JSON had such a feature, check:
http://search.cpan.org/~makamaka/JSON-1.15/lib/JSON.pm#AUTOCONVERT

**Comment by filimonov** [comment]
I don't think that change should be generalized for all cases, it should be an **option** to quote (or not quote, like now) the numbers.

The motivation is:  some parsers are sensetive on quoting, and perl does not have strict types, so the decision of "to quote or not to quote" is not always obvios/predictable.

In perl you can have a number that was used recently as a string (and will be quoted), or you can have a string field which has been created by numeric operation. So quoting strategy currenly depends only on the 'last operation kind' which is not predictable in general (so if last operation was numeric - number will be not quoted, if last operation was string - number will be quoted). 

Currenly i have a situation when some specific JSON parser accepts only quoted format for strings, and both quoted/unquoted format for numbers. And i'm creating lib which can't predict the types of scalars which will be passed as an input (as i can't predict if scalar was created by numeric or string operation).

Once again:
1) i'm creating a library, so i can't predict how the passed scalars was created - by numeric operation or by string operation.
2) i know that parser that will parse the resulting JSON (written in C++) will not accept the string fields (even if they were calculated in perl as numeric values) in unquoted format, and i know that parser can parse quoted numbers. 
3) so the safest strategy is to 'quote-all-around', but currenty i can't force that during JSON encoding without stringifying everything around (which is slow and uneffecient)

p.s. actually the second good resolution of that problem is to change the target parser to allow unquoted numeric-looking strings in string fields. But still older version of that parser will not accept numbers as strings, and may be support for 'predictable' way of quoting should exists in Cpanel::JSON::XS itself (currently quoting depengs of type-sniffing. which can work bad in perl).

**Comment by Grinnz** [comment]
Note that in Cpanel::JSON::XS and JSON::PP, quoting is more predictable: numbers will not be quoted just because they were *used* as a string but only if they are created as a string. Did you consider the type schema solution mentioned? See https://metacpan.org/pod/Cpanel::JSON::XS::Type

**Comment by filimonov** [comment]
> Did you consider the type schema solution mentioned? See https://metacpan.org/pod/Cpanel::JSON::XS::Type

Sounds nice, didn't know about that feature, i'll check that.
