### ISSUE TITLE
Broken metadata

### ISSUE THREAD

**Issue by Grinnz** [rurban/Cpanel-JSON-XS#113]
The metadata included with version 4.03 appears to be broken. There is only META.yml and it is missing lots of things: https://metacpan.org/source/RURBAN/Cpanel-JSON-XS-4.03/META.yml

Compare with https://metacpan.org/source/RURBAN/Cpanel-JSON-XS-4.02/META.json

**Comment by rurban** [comment]
Oops, this was generated by 5.6, my very last test.
The next one will be better.
