### ISSUE TITLE
Feature request: allow_dupkeys

### ISSUE THREAD

**Issue by Grinnz** [rurban/Cpanel-JSON-XS#122]
As a result of https://github.com/rurban/Cpanel-JSON-XS/pull/75 duplicate keys in parsed JSON throw an exception. Relaxed mode allows duplicate keys, but there is no way to allow duplicate keys without turning on relaxed mode. Unlike the other syntax allowed by relaxed mode, duplicate keys are still valid (the spec only says that keys SHOULD be unique). In addition, JSON::PP, JSON::XS, and Mojo::JSON all allow duplicate keys, so this option would help with cross compatibility.

**Comment by rurban** [comment]
Dan Book <notifications@github.com> schrieb am Do., 14. Feb. 2019, 20:25:

> As a result of #75 <https://github.com/rurban/Cpanel-JSON-XS/pull/75>
> duplicate keys in parsed JSON throw an exception. Relaxed mode allows
> duplicate keys, but there is no way to allow duplicate keys without turning
> on relaxed mode.
>
No, to my knowledge we've added an allow_dupkeys option independent of
relaxed.
if not that's a bug, but I believe there's a testcase to turn on only
dupkeys.


Unlike the other syntax allowed by relaxed mode, duplicate keys are still

**Comment by Grinnz** [comment]
There's no option that I can find:

```
> perl -MCpanel::JSON::XS -E'say Cpanel::JSON::XS->VERSION; Cpanel::JSON::XS->new->allow_dupkeys'
4.08
Can't locate object method "allow_dupkeys" via package "Cpanel::JSON::XS" at -e line 1.
```

**Comment by rurban** [comment]
Oops, I see. I went with the shortcut: "relaxed implements allow_dupkeys"
That needs to be added separately of course. Thanks for notifying!

**Comment by rurban** [comment]
Done with 4.09

**Comment by Grinnz** [comment]
Thanks!
