### ISSUE TITLE
Tests failures for perl 5.12.3

### ISSUE THREAD

**Issue by miloja** [rurban/Cpanel-JSON-XS#126]
I'm using perl 5.12.3 built for MSWin32-x86-multi-thread (strawberry perl). Since version 3.0225 01_utf8.t  and 118_type.t  fails.

<pre>
Running test for module 'Cpanel::JSON::XS'
Running make for R/RU/RURBAN/Cpanel-JSON-XS-4.10.tar.gz
  Has already been unwrapped into directory C:\strawberry\cpan\build\Cpanel-JSON-XS-4.10-lqSmij
  Has already been made
Running make test
C:\strawberry\perl\bin\perl.exe "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib\lib', 'blib\arch')" -Mcommon::sense t/*.t
t/00_load.t ................ ok
t/01_utf8.t ................ 1/162
#   Failed test at t/01_utf8.t line 13.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8)'

#   Failed test at t/01_utf8.t line 19.
#                   ''
#     doesn't match '(?-xism:Wide character)'

#   Failed test 'ill-formed utf8 <80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <80 bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <80 bf 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <80 bf 80 bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <80 bf 80 bf 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <80 bf 80 bf 80 bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <80 bf 80 bf 80 bf 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8
f 90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f a0 a1 a2 a3 a4 a5 a6 a7 a8 a9
aa ab ac ad ae af b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 ba bb bc bd be bf> throws error'

#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <c0 20 c1 20 c2 20 c3 20 c4 20 c5 20 c6 20 c7 2
0 c8 20 c9 20 ca 20 cb 20 cc 20 cd 20 ce 20 cf 20 d0 20 d1 20 d2 20 d3 20 d4 20
d5 20 d6 20 d7 20 d8 20 d9 20 da 20 db 20 dc 20 dd 20 de 20 df 20> throws error'

#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <e0 20 e1 20 e2 20 e3 20 e4 20 e5 20 e6 20 e7 2
0 e8 20 e9 20 ea 20 eb 20 ec 20 ed 20 ee 20 ef 20> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f0 20 f1 20 f2 20 f3 20 f4 20 f5 20 f6 20 f7 2
0> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f8 20 f9 20 fa 20 fb 20> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fc 20 fd 20> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <c0> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <e0 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f0 80 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f8 80 80 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fc 80 80 80 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <df> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <ef bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f7 bf bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fb bf bf bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fd bf bf bf bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <c0 e0 80 f0 80 80 f8 80 80 80 fc 80 80 80 80 d
f ef bf f7 bf bf fb bf bf bf fd bf bf bf bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fe> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <ff> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fe fe ff ff> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f0 8f bf bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f8 87 bf bf bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fc 83 bf bf bf bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <c0 af> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <e0 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <e0 80 af> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f0 80 80 af> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f8 80 80 80 af> throws error'
#   at t/01_utf8.t line 164.
#                   ''

#   Failed test 'ill-formed utf8 <fc 80 80 80 80 af> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <c1 bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <e0 9f bf> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <c0 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <e0 80 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f0 80 80 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <f8 80 80 80 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <fc 80 80 80 80 80> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'

#   Failed test 'ill-formed utf8 <c1 9c> throws error'
#   at t/01_utf8.t line 164.
#                   ''
#     doesn't match '(?-xism:malformed UTF-8 character)'
# Looks like you failed 46 tests of 162.
t/01_utf8.t ................ Dubious, test returned 46 (wstat 11776, 0x2e00)
Failed 46/162 subtests 
t/02_error.t ............... ok
t/03_types.t ............... ok
t/04_dwiw_encode.t ......... ok
t/05_dwiw_decode.t ......... ok
t/06_pc_pretty.t ........... ok
t/07_pc_esc.t .............. ok
t/08_pc_base.t ............. ok
t/08_pc_base_nv.t .......... ok
t/09_pc_extra_number.t ..... ok
t/104_sortby.t ............. ok
t/105_esc_slash.t .......... ok
t/106_allow_barekey.t ...... ok
t/107_allow_singlequote.t .. ok
t/108_decode.t ............. ok
t/109_encode.t ............. ok
t/10_pc_keysort.t .......... ok
t/110_bignum.t ............. ok
t/112_upgrade.t ............ ok
t/113_overloaded_eq.t ...... ok
t/114_decode_prefix.t ...... ok
t/115_tie_ixhash.t ......... ok
t/116_incr_parse_fixed.t ... ok
t/117_numbers.t ............ ok
t/118_type.t ............... 1/247
#   Failed test at t/118_type.t line 262.
#                   ''
#     doesn't match '(?-xism:Only one scalar type can be specified in anyof)'

#   Failed test at t/118_type.t line 265.
#                   ''
#     doesn't match '(?-xism:Only one array type can be specified in anyof)'

#   Failed test at t/118_type.t line 268.
#                   ''
#     doesn't match '(?-xism:Only one hash type can be specified in anyof)'

#   Failed test at t/118_type.t line 271.
#                   ''
#     doesn't match '(?-xism:Only one array type can be specified in anyof)'

#   Failed test at t/118_type.t line 274.
#                   ''
#     doesn't match '(?-xism:Only one hash type can be specified in anyof)'

#   Failed test at t/118_type.t line 277.
#                   ''
#     doesn't match '(?-xism:Only one array type can be specified in anyof)'

#   Failed test at t/118_type.t line 280.
#                   ''
#     doesn't match '(?-xism:Only one hash type can be specified in anyof)'

#   Failed test at t/118_type.t line 283.
#                   ''
#     doesn't match '(?-xism:Only scalar, array or hash can be specified in anyo
f)'

#   Failed test at t/118_type.t line 286.
#                   ''
#     doesn't match '(?-xism:Scalar cannot be specified in null_or_anyof)'

#   Failed test at t/118_type.t line 289.
#                   ''
#     doesn't match '(?-xism:Exactly one type must be specified in arrayof)'

#   Failed test at t/118_type.t line 292.
#                   ''
#     doesn't match '(?-xism:Exactly one type must be specified in hashof)'
# Looks like you failed 11 tests of 247.
t/118_type.t ............... Dubious, test returned 11 (wstat 2816, 0xb00)
Failed 11/247 subtests 
t/11_pc_expo.t ............. ok
t/12_blessed.t ............. ok
t/13_limit.t ............... ok
t/14_latin1.t .............. ok
t/15_prefix.t .............. ok
t/16_tied.t ................ ok
t/17_relaxed.t ............. ok
t/18_json_checker.t ........ ok
t/19_incr.t ................ ok
t/20_faihu.t ............... ok
t/20_unknown.t ............. ok
t/21_evans.t ............... ok
t/22_comment_at_eof.t ...... ok
t/23_array_ctx.t ........... ok
t/24_freeze_recursion.t .... ok
t/25_boolean.t ............. ok
t/26_duplicate.t ........... ok
t/30_jsonspec.t ............ ok
t/31_bom.t ................. ok
t/52_object.t .............. ok
t/53_readonly.t ............ ok
t/54_stringify.t ........... ok
t/55_modifiable.t .......... ok
t/96_interop.t ............. ok
t/96_interop_pp.t .......... ok
t/96_mojo.t ................ skipped: Mojo::JSON required for testing interop
t/97_unshare_hek.t ......... ok
t/98_56only.t .............. ok
t/99_binary.t .............. ok
t/zero-mojibake.t .......... ok

Test Summary Report
-------------------
t/01_utf8.t              (Wstat: 11776 Tests: 162 Failed: 46)
  Failed tests:  6, 10, 32, 35, 38, 41, 44, 47, 50, 53, 56
                59, 62, 65, 68, 71, 74, 77, 80, 83, 86
                89, 92, 95, 98, 101, 104, 107, 110, 113
                116, 119, 122, 125, 128, 131, 134, 137
                140, 143, 146, 149, 152, 155, 158, 161
  Non-zero exit status: 46
t/118_type.t             (Wstat: 2816 Tests: 247 Failed: 11)
  Failed tests:  224, 226, 228, 230, 232, 234, 236, 238
                240, 242, 244
  Non-zero exit status: 11
t/30_jsonspec.t          (Wstat: 0 Tests: 686 Failed: 0)
  TODO passed:   381-382
Files=56, Tests=2686, 12 wallclock secs ( 0.83 usr +  0.16 sys =  0.99 CPU)
Result: FAIL
  RURBAN/Cpanel-JSON-XS-4.10.tar.gz
  C:\strawberry\c\bin\dmake.EXE test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports RURBAN/Cpanel-JSON-XS-4.10.tar.gz
</pre>

**Comment by miloja** [comment]
I've made a deeper investigation which shows, that this tests fails because of our custom changes to Test::Builder. The source was such this change:
```diff
--- a/perl/site/lib/Test/Builder.pm
+++ b/perl/site/lib/Test/Builder.pm
@@ -1865,6 +1865,7 @@ sub output {
     if( defined $fh ) {
         $self->{Out_FH} = $self->_new_fh($fh);
     }
+    binmode $self->{Out_FH}, ':encoding(UTF-8)';
     return $self->{Out_FH};
 }
 
@@ -1874,6 +1875,7 @@ sub failure_output {
     if( defined $fh ) {
         $self->{Fail_FH} = $self->_new_fh($fh);
     }
+    binmode $self->{Fail_FH}, ':encoding(UTF-8)';
     return $self->{Fail_FH};
 }
```

The reason was to let polish character be outputed in tests, but looks like it break some other tests. Without this tests runs fine.

**Comment by Grinnz** [comment]
This is not correct to apply to Test::Builder. You need to encode all your data to UTF-8 yourself. The newer Test2 framework has a UTF8 plugin that will do this correctly.

**Comment by rurban** [comment]
Ok, thanks to the explanation. I was worried a bit.
