### ISSUE TITLE
encode_json [!1, !0] doesn't yield "[false, true]"

### ISSUE THREAD

**Issue by akarelas** [rurban/Cpanel-JSON-XS#143]
Documentation [says](https://metacpan.org/pod/Cpanel::JSON::XS#Cpanel::JSON::XS::true,-Cpanel::JSON::XS::false):
```
encode_json [!1, !0]      # yields [false,true]
```

...but this script acts differently:

```
#!/usr/bin/env perl

use v5.30;
use warnings;
use lib '../local/lib/perl5';

use Cpanel::JSON::XS;

say encode_json [!1, !0];
say $Cpanel::JSON::XS::VERSION;
say $^V;
```

Output of the above is:
```
["",1]
4.12
v5.30.0
```

...and not, as the documentation suggests:

```
[false,true]
4.12
v5.30.0
```

My perl 5.30.0 was compiled with plenv, in the standard way that plenv does it.

**Comment by rurban** [comment]
Yes, I had to revert this feature recently due popular demand and forgot to fix the documentation

**Comment by pali** [comment]
@akarelas: As alternative solution you can use:
```perl
use Cpanel::JSON::XS;
use Cpanel::JSON::XS::Type;

print encode_json [!1, !0], [JSON_TYPE_BOOL, JSON_TYPE_BOOL];
```
And it prints:
```
[false,true]
```
