### ISSUE TITLE
Changelog missing for 4.16

### ISSUE THREAD

**Issue by perlpunk** [rurban/Cpanel-JSON-XS#155]
Version 4.16 doesn't have an entry in Changes:
https://metacpan.org/changes/release/RURBAN/Cpanel-JSON-XS-4.16

I stumbled over this while maintaining the perl modules repository in openSUSE Build Service.

**Comment by rurban** [comment]
I wonder if there's an xt test for this?

**Comment by perlpunk** [comment]
That would be good.
I set up https://github.com/perlpunk/perl5-module-meta recently, and it would be great if there was a test module that can cover some of these issues not handled by kwalitee or other existing test modules yet.

**Comment by rurban** [comment]
I've added tests for both. Released with 4.17

**Comment by karenetheridge** [comment]
I use Dist::Zilla::Plugin::Test::ChangesHasContent for that, which generates its own xt/author/changes-has-content.t file, which could be lifted out into its own Test:: module easily enough probably (or just steal its generated content directly for your distribution).

**Comment by Corion** [comment]
I have a slew of tests in [https://github.com/Corion/Dist-Template] (the `template/` directory, but these rely (due to lazyness) on a `Makefile.PL` that will export the module metadata. These author tests could be rewritten to use `META.yml` for example.
