### ISSUE TITLE
Cpanel-JSON-XS 4.18: fatal error: xlocale.h: No such file or directory on Strawberry Perl 5.20.3

### ISSUE THREAD

**Issue by twata1** [rurban/Cpanel-JSON-XS#159]
Hello,

When I tried to `cpan Cpanel::JSON::XS`, I noticed the following message.

(snip)
```
probe for xlocale.h... tmp.c:2:21: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
                     ^
compilation terminated.
not found
```
(snip)

[Environment]

Windows 8.1 (64bit)
Strawberry Perl 5.20.3 (64bit)

Thank you,

**Comment by rurban** [comment]
Yes, that works is indented. Some perl's have a wrong I_LOCALE and HAS_LOCALE setting, esp. after a system upgrade without upgrading perl. So we have to probe for it.
