### ISSUE TITLE
should `is_bool` return true for all values that would be encoded as booleans?

### ISSUE THREAD

**Issue by karenetheridge** [rurban/Cpanel-JSON-XS#162]
```
perl  -MCpanel::JSON::XS -wle'print Cpanel::JSON::XS->new->allow_nonref(1)->encode(!0)'
true
perl  -MCpanel::JSON::XS -wle'print Cpanel::JSON::XS->new->allow_nonref(1)->is_bool(!0)'

```

Should `is_bool` return true if the value would be encoded as a boolean, even when it is not a JSON::PP::Boolean::(true|false)?

**Comment by Grinnz** [comment]
IMO it should be restricted to boolean objects such as decode_json would return. There are other ways to encode to booleans and if they all were true in is_bool it would be of limited use.

**Comment by karenetheridge** [comment]
I would have use for a function that returned true whenever the value would be encoded as a boolean.  Otherwise, I have to do: `$j->encode($value) =~ /^(true|false)$/`.

**Comment by Grinnz** [comment]
If you force the boolean type with JSON_TYPE_BOOL, then standard Perl boolean logic is used. So I think for that it would be more useful to have a function that returns a JSON boolean object or undef if it would not be interpreted as a boolean.

**Comment by rurban** [comment]
> I would have use for a function that returned true whenever the value would be encoded as a boolean. Otherwise, I have to do: `$j->encode($value) =~ /^(true|false)$/`.

Hmm, didn't think of that. But that needs to be the job of a generic Type::Bool method. We shouldn't solve everything, only detect our method results.

**Comment by karenetheridge** [comment]
BTW the documentation for is_bool mentions JSON::XS::true and JSON::XS::false - is this also out of date and should read JSON::PP::Boolean?

      $is_boolean = Cpanel::JSON::XS::is_bool $scalar
           Returns true if the passed scalar represents either "JSON::XS::true" or "JSON::XS::false", two constants that act like 1 and 0, respectively and are used to represent JSON "true" and "false" values in Perl.

**Comment by karenetheridge** [comment]
I decided to not be so clever in my application and just called `is_bool()`. Otherwise, encoding the value and doing a stringwise comparison to `"true"` or `"false"` is a reasonable workaround.
