### ISSUE TITLE
is_bool() should recognize unblessed_bool booleans

### ISSUE THREAD

**Issue by karenetheridge** [rurban/Cpanel-JSON-XS#181]
is_bool() should check for the values `&PL_sv_yes` and `&PL_sv_no`, which is what is produced when decoding booleans when unblessed_bools is set.

In pure perl this can be done with `sub isbool { return 1 if <other checks> ||  \$_[0] == \!!0 || \$_[0] == \!!1 }` -- I expect the XS equivalent is just comparing to &PL_sv_yes directly.

**Comment by karenetheridge** [comment]
oh perhaps not, given https://github.com/rurban/Cpanel-JSON-XS/pull/121

**Comment by rurban** [comment]
Exactly. We need non-readonly copies

**Comment by rurban** [comment]
But we should add support to detect such new booleans, of course.

**Comment by rurban** [comment]
Such support added with PR #198 via CORE_BOOL
