### ISSUE TITLE
with allow_bignum, all floats are inflated to Math::BigFloat

### ISSUE THREAD

**Issue by karenetheridge** [rurban/Cpanel-JSON-XS#187]
This isn't a bug but it's not very efficient to inflate all numbers as Math:: objects, rather than just those that exceed nvsize:

```
perl -MData::Dumper -MCpanel::JSON::XS -wle'my $data = Cpanel::JSON::XS->new->allow_nonref->allow_bignum->decode("2.0"); print Dumper($data)'
$VAR1 = bless( {
                 '_es' => '+',
                 '_e' => bless( [
                                  '0'
                                ], 'Math::BigInt::Calc' ),
                 '_m' => bless( [
                                  '2'
                                ], 'Math::BigInt::Calc' ),
                 'sign' => '+'
               }, 'Math::BigFloat' );
```

(edit: I see this just affects floats, which is not so bad.)

**Comment by rurban** [comment]
I cannot check if the float exceeds the default precision, only the range.
e.g. decode "2.000000000000000000001" needs to convert to bigfloat, but is below NV_MAX. This would only be possible by checking every number for proper round-tripping with the default type, which is equally expensive than converting to bigfloat.
