### ISSUE TITLE
segmentation fault when serializing

### ISSUE THREAD

**Issue by karenetheridge** [rurban/Cpanel-JSON-XS#192]
reference: https://github.com/Sereal/Sereal/issues/266

If there was a FREEZE method that did nothing but die with a helpful message, that would still be better than a segfault. But FREEZE could also emit a hashref containing its constructor options and THAW could read that back in, also.

**Comment by rurban** [comment]
> demerphq: Bug in Cpanel::JSON::XS which is not validating that the "funky" SV it uses is the correct size. https://github.com/Sereal/Sereal/issues/266

**Comment by rurban** [comment]
I've added now a magic to check against in my JSON struct. Fixed all the testcases.
