### ISSUE TITLE
Feature Request: allow_dupkeys extension to actually create an array

### ISSUE THREAD

**Issue by warpspin** [rurban/Cpanel-JSON-XS#193]
Sometimes buggy JSON encoders will create duplicate keys in hashes. A real world example is the output of EXPLAIN FORMAT=JSON in MariaDB before 10.8.

While allow_dupkeys allows to not error on those, most of the data is still lost, as simply the contents of the last key will win. 

An optional setting like e.g. "dupkeys_as_arrayref" could be offered which, if it encounters a duplicate key, will not simply overwrite the existing hash key, but instead convert the hash value into an array reference and push all duplicate keys onto that.

**Comment by rurban** [comment]
Yes, sounds useful to me.

**Comment by rurban** [comment]
in release 4.28
