### ISSUE TITLE
RFE: utf8(0) variant appropriate for byte strings

### ISSUE THREAD

**Issue by FGasper** [rurban/Cpanel-JSON-XS#202]
Consider:
```
> perl -MData::Dumper -MJSON::XS -e'print Dumper( JSON::XS->new()->decode(q<["fooé\uabcd"]>)->[0] )'
$VAR1 = "foo\x{c3}\x{a9}\x{abcd}";
```
The input is a “sensible” JSON string. The output, though, is nonsensical since it outputs a Unicode character after 2 bytes.

`utf8(1)` makes for sensible output:
```
> perl -MData::Dumper -MJSON::XS -e'print Dumper( JSON::XS->new()->utf8(1)->decode(q<["fooé\uabcd"]>)->[0] )'
$VAR1 = "foo\x{e9}\x{abcd}";
```
… which can then be encoded, but that will break if given invalid UTF-8 as part of the JSON payload—which is invalid JSON, of course, but one of the reasons for `utf8(0)` is precisely to allow for, e.g., 0xFF octets in the input.

Of course, changing `utf8(0)`’s behaviour is likely to break someone’s code out there.

Ideally Cpanel::JSON::XS should implement an alternate `utf8(…)` mode that behaves as `utf8(0)` does currently but _does_ encode `\uabcd` as UTF-8. I’m unsure of the best interface for that, though. Ideally `utf8(…)` wouldn’t be a boolean, so there could simply be an additional mode added, but that train already left the station.

**Comment by Grinnz** [comment]
To add: the encoding of the input is assumed no matter what. With utf8(0) (the default when using an object like this) it is assumed to be decoded characters. Thus the output is perfectly sensical for the characters that correlate to the bytes you've provided to it.

**Comment by FGasper** [comment]
> you didn't pay attention to the encoding

I did; I just intend for bytes-in-bytes-out to be the behaviour.

I see now, though, that the documentation does disclaim support for having utf8(0) take (and output) byte/UTF-8 strings. FWIW I think this is a less-than-useful assumption, and there’s as legitimate of a use case for bytes-in-bytes-out as for chars-in-chars-out.

What if utf8() were to be redefined to take something like `utf8(UTF8_NONE)`, `utf8(UTF8_ALL)`, and `utf8(UTF8_ONLY_U)`. Those constants would be 0, 1, and 2. Thus existing applications keep working, and a “super-boolean” is (nominally) avoided.

**Comment by haarg** [comment]
Can you show an example of what behavior you want? It's not obvious what you are looking for here. JSON is always a unicode text string, and the utf8 option doesn't change that. All it does is cause a UTF-8 encoding/decoding step to be done along with the JSON encoding/decoding.

**Comment by FGasper** [comment]
@haarg This is what I envision:
```
> perl -MData::Dumper -MJSON::XS -e'print Dumper( JSON::XS->new()->utf8(UTF8_BYTES)->decode(q<["fooé\uabcd"]>)->[0] )'
$VAR1 = "foo\x{c3}\x{a9}\x{ea}\x{af}\x{8d}";
```
UTF8_BYTES would be like utf8(0), but decode() would turn `\u....` sequences into UTF-8.

Context: Right now, utf8(0) _almost_ allows for JSON-decode to work on byte/UTF-8 strings. That’s useful behaviour, and the fact that it subtly doesn’t _quite_ work is a shin-bumper for us.

**Comment by Grinnz** [comment]
JSON decode without UTF-8 decoding is not possible on byte strings for exactly the reason you mention: there are escape sequences which are not affected by encoding. You must decode JSON bytes from UTF-8 before decoding them from JSON to avoid this mixed encoding state. Any option that implies otherwise would be just as dangerous to support.

**Comment by FGasper** [comment]
@Grinnz Where is the danger if decode() were to be able to turn JSON `\uabcd` into Perl `"\xea\xaf\x8d"`?

**Comment by Grinnz** [comment]
Nevermind the danger, that's nonsensical; no part of the JSON decoding operation is defined to turn a unicode character escape into bytes. You would end up with a patently incorrect data structure (imagine if the unicode character was in a hash key, for example).

**Comment by Grinnz** [comment]
The danger I referenced that such an operation would promote is the implication that JSON decode on bytes is a sensible operation. It is not.

**Comment by FGasper** [comment]
> The danger I referenced that such an operation would promote is the implication that JSON decode on bytes is a sensible operation. It is not.

I know this was just a misstatement, but decode($bytes) is the norm since JSON defines a character encoding. The decoder’s output is the issue.

> You would end up with a patently incorrect data structure (imagine if the unicode character was in a hash key, for example).

I’m probably just missing something, but I don’t take your meaning. Hash keys can be UTF-8 sequences … ?

> no part of the JSON decoding operation is defined to turn a unicode character escape into bytes.

No part of the JSON decoding operation envisions forgoing the UTF-8 decode, either, right? Yet that‘s exactly what this module does, and by default (assuming OO usage).

I’m still not seeing any _technical_ reason why the idea of encoding \u sequences during JSON decode is any more “wrong” than forgoing the UTF-8 decode. Again, I’m probably just missing something … could you flesh out what the hash-key problem is, for example?

The fact of that default, and bytes-in-bytes-out being Perl’s default—even in the latest feature bundle—leads me to suspect quite a lot of Perl code out there does bytes-to-bytes JSON decode. If this _is_, in fact, ultimately a non-starter, then I’ll happily submit a docs patch to discourage it more explicitly.

**Comment by Grinnz** [comment]
> > The danger I referenced that such an operation would promote is the implication that JSON decode on bytes is a sensible operation. It is not.
> 
> I know this was just a misstatement, but decode($bytes) is the norm since JSON defines a character encoding. The decoder’s output is the issue.

It was not a misstatement. decode($bytes) only works on bytes when the first operation is to decode the bytes from UTF-8. By "JSON decode" I was referencing the subsequent conversion from JSON string to data structure. Unfortunately unambiguous language is somewhat impossible in this space.

> 
> > You would end up with a patently incorrect data structure (imagine if the unicode character was in a hash key, for example).
> 
> I’m probably just missing something, but I don’t take your meaning. Hash keys can be UTF-8 sequences … ?

They cannot. Hash keys are Perl strings, which are sequences of ordinals with no inherent meaning. If a JSON string contains a hash key with a unicode escape, and you decoded that to anything other than a string with the ordinal of that unicode codepoint, you would create the wrong data structure and would not be able to access that data at the expected hash key.

> 
> > no part of the JSON decoding operation is defined to turn a unicode character escape into bytes.
> 
> No part of the JSON decoding operation envisions forgoing the UTF-8 decode, either, right? Yet that‘s exactly what this module does, and by default (assuming OO usage).

It does not; JSON decoding without a preceding UTF-8 decode is only for usage on a string which has already been UTF-8-decoded. Any other usage is incorrect.

> 
> I’m still not seeing any _technical_ reason why the idea of encoding \u sequences during JSON decode is any more “wrong” than forgoing the UTF-8 decode. Again, I’m probably just missing something … could you flesh out what the hash-key problem is, for example?

JSON decode is a well defined operation and cannot result in a data structure containing anything other than the ordinal represented by the escape sequence. 

> The fact of that default, and bytes-in-bytes-out being Perl’s default—even in the latest feature bundle—leads me to suspect quite a lot of Perl code out there does bytes-to-bytes JSON decode. If this _is_, in fact, ultimately a non-starter, then I’ll happily submit a docs patch to discourage it more explicitly.

A lot of Perl code uses decode_json which is equivalent to Some::JSON::Module->new->utf8->decode to avoid exactly this problem. Any other code is likely only operating on ASCII.

**Comment by FGasper** [comment]
The JSON spec defines a character encoding; thus, a proper JSON encode includes a UTF-8 encode. Thus, a proper JSON _decode_ includes a UTF-8 decode. Thus, `utf8(0)`, as it stands now, already effects nonstandard behaviour. It’s useful, but it’s not proper JSON encode/decode.

In other words, every proper JSON decode is “without a preceding UTF-8 decode”. A JSON decode _with_ a preceding UTF-8 decode would mean, overall, a double UTF-8 decode.

Aside: JavaScript’s JSON.parse also isn’t a full decode for the same reason. A full JSON decode would take a Uint8Array as argument, but that’s much less useful in JS than accepting a string.

> If a JSON string contains a hash key with a unicode escape, and you decoded that to anything other than a string with the ordinal of that unicode codepoint, you would create the wrong data structure and would not be able to access that data at the expected hash key.

This isn’t true, though, because the expected hash key is the UTF-8-encoded form of the hash key:
```
perl -MCpanel::JSON::XS -e'my $j = Cpanel::JSON::XS->new()->utf8(UTF8_BYTES); my $json = q<{"\u00e9": foo}>; my $hr = $j->decode($json); print $hr->{"é"}'
```
The above would print “foo”. (Assuming a UTF-8 terminal, of course.)

-----
It sounds like your objection, @Grinnz, is ultimately “that wouldn’t be proper JSON”. Cpanel::JSON::XS already, though, implements several features that aren’t proper JSON: comments, latin1(), etc. My point is that this is _useful_, internally-consistent behaviour. Moreover, it also fits better with the default behaviour of both Perl and this very module (in OO mode).

**Comment by Grinnz** [comment]
> This isn’t true, though, because the expected hash key is the UTF-8-encoded form of the hash key:

It would not: the hash key the JSON provides is "\N{U+00E9}". You've accessed a different hash key, so your code is wrong. It's important that the decoded data structure can be accessed by correct code.

Once again, precise language is difficult, but decoding with utf8(0) is only allowed when the UTF-8 decoding step is assumed to have been performed already, which is somewhat common when applications handle decoding in transport (such as in Mojolicious). It should never be used when the UTF-8 decoding step has not been performed.

**Comment by FGasper** [comment]
You’re applying a notion of “correct” that doesn’t fit my circumstance. In our application `é` is always 2 Perl code points. Thus, for us JSON `"é\u00e9"` must somehow yield Perl `\xc3\xa9\xc3\xa9`, even if it’s a hash key.

Ordinarily `encode_utf8( json_decode($json) )` could achieve this; unfortunately, though, we have existing APIs that expect to receive arbitrary octet sequences within JSON strings. I’m assuming we need to preserve that functionality as we try to fix the handling of `\u....` sequences.

We can patch the JSON decoder locally—it doesn’t look like a hard change to make—but I suspect this mode of operation will be at least as useful as several of the other configurations C::J::XS already supports. Thus I’m surprised @rurban agrees with you that this is an “invalid” request, but hey.

**Comment by Grinnz** [comment]
> You’re applying a notion of “correct” that doesn’t fit my circumstance. In our application `é` is always 2 Perl code points. Thus, for us JSON `"é\u00e9"` must somehow yield Perl `\xc3\xa9\xc3\xa9`, even if it’s a hash key.

\u00e9 represents a single unicode character. any purported JSON decode that results in something other than that would be incorrect. I'm not sure how that can be disagreed with. You may apply other logic in your application to do something other than a JSON decode, but that doesn't seem to me reasonable for a JSON decoder to implement, and cause further confusion in an already very confused process.

**Comment by Grinnz** [comment]
> Ordinarily `encode_utf8( json_decode($json) )` could achieve this; unfortunately, though, we have existing APIs that expect to receive arbitrary octet sequences within JSON strings. I’m assuming we need to preserve that functionality as we try to fix the handling of `\u....` sequences.

This would be an unreasonable requirement; there is no way to preserve arbitrary octets while also correctly interpreting unicode escapes except by interpreting the octets as characters instead of bytes.

**Comment by FGasper** [comment]
> You may apply other logic in your application to do something other than a JSON decode, but that doesn't seem to me reasonable for a JSON decoder to implement

I might agree with you but for the fact that this module _already_ implements a number of nonstandard behaviours, precisely because, despite being nonstandard, they’re useful. I mean, utf8() own docs exemplify the nonstandard behaviour of using an encoding _other_ than UTF-8 for JSON, which is now forbidden.

The idea that “this swiss-army-knife with 27 sharp edges doesn’t need a 28th” isn’t unreasonable, but I think you’re underestimating the number of likely Perl code bases that misuse utf8(0) on byte strings, and discounting the workflow without an actual _technical_ basis.

> there is no way to preserve arbitrary octets while also correctly interpreting unicode escapes except by interpreting the octets as characters instead of bytes

Throwing down the gauntlet, hm? ;-)

If the decoder outputs the UTF-8-encoded form of, e.g., `"\u00e9"` rather than the Unicode literal, I don’t see how that falls over. We’ve been using utf8(0) on byte strings for a very long time. Unicode escapes are the only problem we know of. Changing how the decoder handles those doesn’t seem to require any change elsewhere.

**Comment by karenetheridge** [comment]
> If the decoder outputs the UTF-8-encoded form of, e.g., "\u00e9" rather than the Unicode literal

What does this mean? `"\u00e9"` is the json-encoding of a string (in ascii mode). The literal character corresponding to that string is `é`. That's all there is.

```
$; perl -CAS -MCpanel::JSON::XS -wle'use utf8; my $str = "é\x{00e9}"; print Cpanel::JSON::XS->new->utf8(1)->ascii->encode([$str])'
["\u00e9\u00e9"]

$; perl -CAS -MData::Dumper -MCpanel::JSON::XS -wle'use utf8; print Dumper(Cpanel::JSON::XS->new->utf8(0)->ascii->decode(q{["é\u00e9"]}))'
$VAR1 = [
          "\x{e9}\x{e9}"
        ];
```

You seem to be very confused as to what data you're actually putting in and getting out. I suggest using Devel::Peek to be sure.  If you don't want to do a utf8-decoding pass as you json-decode your strings, then use `->utf8(0)`. That's exactly what it does and you don't need anything else.

**Comment by FGasper** [comment]
>  If you don't want to do a utf8-decoding pass as you json-decode your strings, then use ->utf8(0). That's exactly what it does and you don't need anything else.

Actually, no. As @Grinnz pointed out—and as I’d either overlooked or forgotten—utf8(0) is for _decoded_ (i.e., character/text) strings, not byte strings. It serves the use case where both inputs and outputs to decode & encode functions already _are_ decoded. So, there is no legitimate use case for utf8(0)->decode() without a UTF8-decode either as part of the JSON decode or around it.

What I propose is to fix that by adding a 3rd utf8() mode, identical to utf8(0) except for decoding `"\u...."` as UTF-8 sequences.

>  I suggest using Devel::Peek

As an aside: if I didn’t know better I might think you wanted me here to consider “everyone’s favourite SV flag”. I myself only look at Devel::Peek when I specifically want SV internals.

**Comment by karenetheridge** [comment]
> utf8(0) is for decoded (i.e., character/text) strings, not byte strings. It serves the use case where both inputs and outputs to decode & encode functions already are decoded. So, there is no legitimate use case for utf8(0)->decode() without a UTF8-decode either as part of the JSON decode or around it.

`->utf8(0)` just means "don't do a UTF8-decoding/encoding step". The presumption is that you've already got decoded characters, but it works perfectly well for utf8-encoded strings that you want to stay as encoded strings, because the json markup characters (`"`", `[`, `]`, `{`, `}` etc) are all ascii and come out the same either way. Yes, you've now got encoded strings in your data structure, but presumably you wanted that, right? And that's on you to keep track of that fact so you don't later end up with mojibaked strings in your application.

> I myself only look at Devel::Peek when I specifically want SV internals.

Sometimes you  need to look at the SV internals while debugging, to be sure that you're actually ending up with the strings or bytes that you expected to. For example, early on in this thread you failed to recognize the significance of using `-CAS` in a oneliner, or `use utf8;` when using literal non-ascii characters.

This entire thread sounds like your application wants to use downgraded bytestrings everywhere and are struggling with how to achieve that. That's not best practice (you should encode and decode on the boundaries of your application), but every application has warts and you have acknowledged that.

**Comment by Grinnz** [comment]
> > utf8(0) is for decoded (i.e., character/text) strings, not byte strings. It serves the use case where both inputs and outputs to decode & encode functions already are decoded. So, there is no legitimate use case for utf8(0)->decode() without a UTF8-decode either as part of the JSON decode or around it.
> 
> `->utf8(0)` just means "don't do a UTF8-decoding/encoding step". The presumption is that you've already got decoded characters, but it works perfectly well for utf8-encoded strings that you want to stay as encoded strings, because the json markup characters (`"`", `[`, `]`, `{`, `}` etc) are all ascii and come out the same either way.

It doesn't work for utf8-encoded strings because of unicode escapes, which only translate to decoded characters. Thus why it's only reasonable to expect a JSON decoder to decode to unicode text.

**Comment by FGasper** [comment]
> The presumption is that you've already got decoded characters, but it works perfectly well for utf8-encoded strings that you want to stay as encoded strings …

It works perfectly well until someone sends a Unicode escape. We need that escape to map to UTF-8, not to a Unicode character.

> early on in this thread you failed to recognize the significance of using -CAS in a oneliner, or use utf8; when using literal non-ascii characters

Respectfully, I think you misread me. I understand those fine.

> This entire thread sounds like your application wants to use downgraded bytestrings everywhere and are struggling with how to achieve that. That's not best practice (you should encode and decode on the boundaries of your application), but every application has warts and you have acknowledged that.

FWIW I’m not really struggling with “how to achieve”; the needed change is simple. We also don’t really care about upgraded/downgraded. I just see this as useful enough behaviour for upstream. No one seems to agree, though, so hey.

**Comment by Grinnz** [comment]
Suggestion (idea by @karenetheridge): pre-process the JSON file, replacing \uXXXX with unicode escape sequences of the UTF-8 encoding of that character (i.e. `\u00e9` -> `\u00c3\u00a9`). Then decode and encode with utf8(0) to treat the bytes as characters as you attempted to do. Quite ill-advised and the decoded data will not match your input file as described before, but easier than patching a cpan module.

**Comment by Grinnz** [comment]
Note that whatever you do, you're going to have problems interpreting high-ordinal unicode characters (over U+FFFF) that per the JSON spec get encoded as UTF-16 surrogate pair escapes.

**Comment by FGasper** [comment]
> Note that whatever you do, you're going to have problems interpreting high-ordinal unicode characters (over U+FFFF) that per the JSON spec get encoded as UTF-16 surrogate pair escapes.

The test in the PR demonstrates that surrogates work as needed, i.e., they get output as the UTF-8 of the intended Unicode character.

**Comment by rurban** [comment]
As said in the PR #203: I see why Felipe wants utf8(0) to still decode \u codepoints. For me it looks like an error should be thrown instead.
But all this is up for JSON upstream to decide, not here.
