### ISSUE TITLE
Bug: allow_barekey decodes UTF-8 differently with and without quotes

### ISSUE THREAD

**Issue by warpspin** [rurban/Cpanel-JSON-XS#209]
If the allow_barekey option is enabled, and the input string is UTF-8, and a bare key in a hash contains a UTF-8 character, the Perl UTF-8 flag is not set on the key in the resulting hash. If the key is put in quotes, it is properly set.

Please see the attached test script. Intuition would say, that it prints 1 and 2. It instead only prints 2, as on the first decode, the resulting key is not found, as it's instead put with its raw UTF-8 bytes into the hash but not marked as utf8.

[test.pl.txt](https://github.com/rurban/Cpanel-JSON-XS/files/10546314/test.pl.txt)

**Comment by rurban** [comment]
yes, the barekey option went the fast path, without setting the utf8 flag.
will fix it
