### ISSUE TITLE
builtin::true and builtin::false

### ISSUE THREAD

**Issue by rohanc** [rurban/Cpanel-JSON-XS#214]
Perl 5.36 comes with [stable boolean tracking](https://perldoc.perl.org/perldelta#Stable-boolean-tracking). Does this open up any new options for encoding JSON using Cpanel::JSON::XS?

I'm attracted to the prospect of building Perl data structures like `{logging: true}` rather than having to do `{logging: \1}` to get "[logging:true]" in JSON, even though it's more typing.

Here's some test code:

```
use v5.36;
no warnings (qw/experimental::builtin/);
use builtin (qw/is_bool true false/); #  true false/);
use Cpanel::JSON::XS;
my $coder=Cpanel::JSON::XS->new;
$coder->canonical(1);
say $coder->encode({testing=>true,verbose=>false}); # outputs {"testing":1,"verbose":""}
say $coder->encode({testing=>\1,verbose=>\0}); # outputs {"testing":true,"verbose":false}`
```

Is encoding of builtin::true and builtin::false to JSON booleans something that could be enabled in this project? And maybe decoding as well?

I haven't thought carefully about what the implications would be for round-tripping and compatibility with other Perl JSON libraries. JSON:PP has already modified their [is_bool](https://metacpan.org/pod/JSON::PP#JSON::PP::is_bool) method to recognise builtin::true.

```
use v5.36;
no warnings (qw/experimental::builtin/);
use builtin (qw/is_bool true false/);
use JSON::PP ();
use JSON::XS ();
use Cpanel::JSON::XS ();
say JSON::PP::encode_json([true]); # gives: true
say JSON::XS::encode_json([true]); # gives: ["1"]
say Cpanel::JSON::XS::encode_json([true]); # gives: [1]
```

JSON::PP can also be made to decode JSON bool into builtin::true etc:
```
use v5.36;
use JSON::PP ();
use Devel::Peek qw( Dump );

my $coder=JSON::PP->new;
$coder->core_bools(1);
my $data=$coder->decode("[true]"); 
Dump $$data[0];
```
which outputs
```
SV = PVNV(0xaaaae0d029c0) at 0xaaaae0d91c80
  REFCNT = 1
  FLAGS = (IOK,NOK,POK,IsCOW,pIOK,pNOK,pPOK)
  IV = 1
  NV = 1
  PV = 0xaaaab1f00cb8 "1" [BOOL PL_Yes]
  CUR = 1
  LEN = 0
```

JSON::XS can be made to decode in the same way with
`$coder->boolean_values(builtin::false,builtin::true);`

I note that there were discussions about doing something similar for !0 and !1 in #39 and #180 but there didn't seem to be any clear resolution.

**Comment by rurban** [comment]
Thanks for the good test cases. 
Many people do have different opinions about this. But JSON::PP should be matched

**Comment by rurban** [comment]
so encode should detect builtin::true, and decode optionally on core_bools

**Comment by karenetheridge** [comment]
> so encode should detect builtin::true, and decode optionally on core_bools

That sounds reasonable to me. I expect that most of the time decoding to a core bool would make sense, but there might be a reason why it should be disabled (e.g. to cope with older code that looks explicitly for JSON::PP::Booleans?) so leaving a way to turn it off would be good.

**Comment by rohanc** [comment]
I agree with @karenetheridge that it would be useful to control the decoding behaviour. Both JSON::PP and JSON::XS allow this via the [boolean_values](https://metacpan.org/pod/JSON::PP#boolean_values) method.

If this gets adopted and the default is off, I'll be looking for a way to turn it on globally, especially when I'm using tools like Mojolicious, where Cpanel::JSON::XS is [used internally](https://github.com/mojolicious/mojo/blob/main/lib/Mojo/JSON.pm).

**Comment by karenetheridge** [comment]
I have prepared support in JSON::Maybe::XS to support recognizing core booleans in its `is_bool()` interface, but I will wait until Cpanel::JSON::XS supports them before releasing -- otherwise, there might be surprising behaviour due to the mismatch of the results of `is_bool()` and serializing those booleans.

**Comment by rurban** [comment]
Yes, the [boolean_values](https://metacpan.org/pod/JSON::PP#boolean_values) method will also be in, to provide the same API as JSON::PP. I'm just a bit too busy right now

**Comment by rurban** [comment]
I"ve delayed this feature for the 2.78 fixes for the 5.38 release, because I couldn't get it right yet. XS specialist help appreciated.  I took the JSON::PP t/core_bools.t as reference.

**Comment by abraxxa** [comment]
@rurban Why is this closed before a version with the core bools support is released to CPAN?

**Comment by johannessen** [comment]
```sh
perl -MCpanel::JSON::XS -E 'say Cpanel::JSON::XS->VERSION'
# 4.38
perl -MCpanel::JSON::XS -E 'my $x = !!1; say encode_json [$x]'
# [true]
perl -MCpanel::JSON::XS -Mbuiltin=is_bool \
  -E 'say is_bool( Cpanel::JSON::XS->new->unblessed_bool->decode(q<[true]>)->[0] )'
# 1
```

@abraxxa As you can see here, [Cpanel::JSON::XS version 4.38](https://metacpan.org/release/RURBAN/Cpanel-JSON-XS-4.38) includes core bools support, and it was released to CPAN months ago. Are you saying there’s an issue with it? Or are you saying it should have been released earlier?

**Comment by johannessen** [comment]
To ensure backwards compatibility, JSON decoders don’t return core bools automatically. You have to specifically request them, as I did with `unblessed_bool` in the example. (I think `core_bools` works as well.)

So, in your case, I think that’s something you would need to solve with Config::Any. It would need to pass that option through to the JSON decoder. I’m not familiar with Config::Any myself and don’t know if that’s currently possible. I see there’s some related discussion in [RT 70779](https://rt.cpan.org/Public/Bug/Display.html?id=70779), but didn’t investigate further.

**Comment by abraxxa** [comment]
Yes, but those two methods get_core_bools and core_bools haven't been added so far to a CPAN released version of Cpanel::JSON::XS as far as I can tell.
At least they are undocumented.

**Comment by johannessen** [comment]
Maybe? But as I demonstrated above, `unblessed_bool` *does* work in the released version.

I do agree with you that it’s not well documented though.

**Comment by abraxxa** [comment]
Config::Any allows configuring Config::General, but it seems not for Cpanel::JSON::XS: https://metacpan.org/dist/Config-Any/source/lib/Config/Any/JSON.pm#L54

**Comment by johannessen** [comment]
Again, that’s something you would need to solve with Config::Any.

Cpanel::JSON::XS is working as intended, and the current version on CPAN supports core bools just fine.

**Comment by abraxxa** [comment]
Of course @Config::Any!
Just found https://rt.cpan.org/Ticket/Display.html?id=70779 which was the request to add JSON parser config support but stalled.

Are there plans to merge the `old/gh214-true` branch to enable returning builtin boolean values instead of 1 and 0?

**Comment by rurban** [comment]
> 
> Are there plans to merge the `old/gh214-true` branch to enable returning builtin boolean values instead of 1 and 0?

No. This was in for a while, until I was forced to revert that. If you can persuade upstream to do that, I'm fine with following. But I will not deviate

**Comment by abraxxa** [comment]
Is there a p5p thread or somewhere else that I can read?
