### ISSUE TITLE
allow_singlequote should also allow \'

### ISSUE THREAD

**Issue by warpspin** [rurban/Cpanel-JSON-XS#216]
In my opinion, if allow_singlequote option is enabled, it should also be possible to escape it using a backslash sequence. Right now it will error with a "illegal backslash escape sequence in string" error.

With allow_singlequote disabled, \\' should stay a "illegal backslash escape sequence in string", though, as it currently is, to stay JSON standard compliant.

[test2.pl.txt](https://github.com/rurban/Cpanel-JSON-XS/files/11420859/test2.pl.txt)

**Comment by rurban** [comment]
care for a patch?

**Comment by warpspin** [comment]
Ok, sent you a pull request with a patch.
