### ISSUE TITLE
Inconsistent behavior between decoding escaped and unescaped surrogates

### ISSUE THREAD

**Issue by G4Vi** [rurban/Cpanel-JSON-XS#233]
```perl
my $scalar = qq|"\\uD83F"|;
Cpanel::JSON::XS->new->allow_nonref->decode($scalar);
```

Fails as expected with
`missing low surrogate character in surrogate pair, at character offset 7 (before """) at`

```perl
my $scalar = qq|"\x{D83F}"|;
Cpanel::JSON::XS->new->allow_nonref->decode($scalar);
```

No error is produced and the resulting string has invalid Unicode.

This is a particularly a problem with `->utf8` is specified as, I'd expect only valid Unicode to be decoded. However, it seems best to handle the escaped and non-escaped codepoints the same regardless of whether UTF-8 decoding is done.

Failing on invalid surrogate codepoints appears to already be on the TODO list for Cpanel::JSON::XS given https://github.com/rurban/Cpanel-JSON-XS/blob/fecd02eff8f641f2c8f30670e5166f8d0b57b4b5/t/30_jsonspec.t#L19

This is also an issue with JSON::PP: https://github.com/makamaka/JSON-PP/issues/91 and JSON::XS (I also emailed Marc Lehmann). However, I think there's merit to implementing this ahead of them as those implementations are already behind Cpanel::JSON::XS as they don't error on `SUPER` (greater than `U+10FFFF`).

**Comment by rurban** [comment]
Fixed with 4.39
