### ISSUE TITLE
Move common::sense to suggests?

### ISSUE THREAD

**Issue by shadowcat-mst** [rurban/Cpanel-JSON-XS#36]
Given some versions of CPAN.pm default to installing recommends, it seems worth moving common::sense out to suggests to make it less likely people don't get it unexpectedly.

Thoughts?

**Comment by karenetheridge** [comment]
Does common::sense do anything for Cpanel::JSON::XS? I wonder why it's there at all.

**Comment by rurban** [comment]
I use it during the tests to be sure to be upwards compatible, even if refusing to do its run-time checks.

**Comment by rurban** [comment]
Thanks, merged. Will be in 3.0116

**Comment by shadowcat-mst** [comment]
Nobody deprecated recommends - but people often assume recommends is things you should want to have installed, which makes suggests more appropriate nonetheless.

Thanks for fixing this.
