### ISSUE TITLE
Option for stringification of objects

### ISSUE THREAD

**Issue by Grinnz** [rurban/Cpanel-JSON-XS#37]
Based on the behavior of Mojo::JSON and some discussion on dealing with references there, this is a suggestion for an option to stringify blessed references instead of encoding to null or throwing an exception, when no TO_JSON method is found. Perhaps stringify all objects such as Mojo::JSON does currently (better for debugging), or another possibility is to detect if the object has overload defined. Either way would make Cpanel::JSON::XS compatible with Mojo::JSON for structures which contain e.g. Mojo::ByteStream objects, or DateTime objects.

**Comment by rurban** [comment]
I agree. I've tried both variants back and forth, and there needs to be an option.

**Comment by kraih** [comment]
:+1: I would really like to use that option.

**Comment by rurban** [comment]
The counter argument is explained here: https://www.youtube.com/watch?v=Gzx6KlqiIZE&feature=youtu.be

serializers who allow deserialization of objects, and JSON and Data::MessagePack are the only ones currently who do not, are unsafe.
our security team has lot of troubles with those serializers.

**Comment by Grinnz** [comment]
This feature does not allow for deserialization of objects, it is only an additional way to serialize them; when deserialized, they will still always be strings.

**Comment by mrenvoize** [comment]
Seems like a nice to have :)

**Comment by nnutter** [comment]
:+1: Being able to fallback on stringification of an object for serialization would be more useful than just getting `null`.  Could do something like `convert_blessed([qw(TO_JSON to_string)])` or make another option like `stringify_blessed(1)` that just did `$obj . ''`.

**Comment by zoffixznet** [comment]
:+1:

**Comment by rurban** [comment]
Can somebody come up with a testcase please?
The true and false values would be \1 and \0, the Mojo::JSON docs are wrong there.


This test works ok:
```
use Test::More;
BEGIN {
  eval "require Mojo::JSON;";
  if ($@) {
    plan skip_all => "Mojo::JSON required for testing interop";
    exit 0;
  } else {
    plan tests => 6;
  }
}

use Mojo::JSON ();
use Cpanel::JSON::XS ();

my $booltrue = q({"is_true":true});
my $boolfalse = q({"is_false":false});
#my $boolpl     = { is_false => \0, is_true => \1 };
my $js = Mojo::JSON::decode_json( $booltrue );
is( $js->{is_true}, 1 );

my $cjson = Cpanel::JSON::XS->new;
is($cjson->encode( $js ), $booltrue)
  or diag "\$Mojolicious::VERSION=$Mojolicious::VERSION,".
  " \$Cpanel::JSON::XS::VERSION=$Cpanel::JSON::XS::VERSION";

$js = Mojo::JSON::decode_json( $boolfalse );
is( $cjson->encode( $js ), $boolfalse );
is( $js->{is_false}, 0 );

$js = $cjson->decode( $booltrue );
is( $cjson->encode( $js ), $booltrue ) or diag(ref $js->{is_true} );
$js = $cjson->decode( $boolfalse );
is( $cjson->encode( $js ), $boolfalse ) or diag(ref $js->{is_false} );
```

**Comment by Grinnz** [comment]
This issue is regarding stringification of objects, booleans are not a problem.

**Comment by rurban** [comment]
So adding an option `stringify_blessed`, which does the stringify overload. What else?

**Comment by Grinnz** [comment]
Here's a basic test case:

```
use Test::More;
use Cpanel::JSON::XS ();
use Time::Piece;

my $json = Cpanel::JSON::XS->new->allow_blessed(1);
# $json->stringify_blessed(1); ??? possible option

my $time = localtime;
my $encoded = $json->encode({time => $time});
my $decoded = $json->decode($encoded);
ok(defined($decoded->{time}), 'Time::Piece object was stringified') or diag($encoded);

done_testing;
```

**Comment by rurban** [comment]
See branch `stringify_blessed-gh37` WIP

**Comment by rurban** [comment]
I couldn't get the AMAGIC call yet working, so I'll postpone this feature.

**Comment by rurban** [comment]
I'll keep the name `convert_blessed`. No need for an extra `stringify_blessed`.

**Comment by zoffixznet** [comment]
:+1:

**Comment by rurban** [comment]
The feature works now >5.8. 
The only question remaining is if to always embed the overloaded stringification into ""?
e.g.
```
$json->encode( { time => localtime } ) eq '{"time":"Thu Nov 26 11:15:16 2015"})
```
or  '{"time":Thu Nov 26 11:15:16 2015}

Without embedded " it would allow to stringify into native js primitives, which might be a wanted feature.
like  '{"time": { someother_object: 1} }', but then you should really use the TO_JSON method.

So I enforce "" now. It makes it easy to use normal default perl stringifications.

**Comment by kraih** [comment]
Agreed, enforcing `""` seems much better. Anyone who wants to generate something else than a JSON string can just use `TO_JSON`.

**Comment by rurban** [comment]
All tests pass, I'll merge it now to master

**Comment by Grinnz** [comment]
This does not seem to be working properly in 3.0204 with Mojo::ByteStream objects, it's outputting invalid JSON, not sure why. I reproduced the overload that package uses below.
```
$ perl -MCpanel::JSON::XS -E'package Foo { use overload q{""} => sub { ${$_[0]} }, fallback => 1; sub new { bless \(my $dummy = "foo"), shift } } say Cpanel::JSON::XS->new->convert_blessed->encode([Foo->new])'
[foo]
```

**Comment by Grinnz** [comment]
More test failures, these aren't blessed references:
```
$ perl -MCpanel::JSON::XS -E'say Cpanel::JSON::XS->new->allow_blessed->convert_blessed->encode({true => \"some true value"})'
{"true":some true value}
$ perl -MCpanel::JSON::XS -E'say Cpanel::JSON::XS->new->allow_blessed->convert_blessed->encode({false => \""})'
{"false":}
$ perl -MCpanel::JSON::XS -E'say Cpanel::JSON::XS->new->allow_blessed->convert_blessed->encode({false => \!!""})'
{"false":}
```
