### ISSUE TITLE
is_bool() is no longer safe to run on unblessed references

### ISSUE THREAD

**Issue by oschwald** [rurban/Cpanel-JSON-XS#53]
As of [this commit](https://github.com/rurban/Cpanel-JSON-XS/commit/387ca675764e6673e460ee6dc7a5362684bc2e69), `is_bool()` throws an exception on unblessed references. For instance:

```
Cpanel::JSON::XS::is_bool([])
```
produces:

```
Runtime error: Can't call method "isa" on unblessed reference at lib/site_perl/5.20.2/x86_64-linux/Cpanel/JSON/XS.pm line 1982.
```

**Comment by rurban** [comment]
Thanks. I knew that Ether's request to change that to this isa method was wrong.

**Comment by Grinnz** [comment]
It was not wrong, but you should check blessed($_[0]) instead of ref($_[0]) before calling isa method on it.

**Comment by rurban** [comment]
That is exactly what I didn't want to do. That's why I prefered UNIVERSAL::isa

**Comment by Grinnz** [comment]
OK. The reason for preferring the blessed and method check is because of the warning here, I believe: https://metacpan.org/pod/UNIVERSAL#EXPORTS But if you're not concerned with classes that might overload isa to pretend to be booleans or something, that should be fine.

**Comment by rurban** [comment]
Overloading isa for those booleans is entirely ok. The problem is the massive Scalar::Util + DynaLoader overhead. At least with perl5 proper. With cperl it's much better.

**Comment by oschwald** [comment]
Thanks!
