### ISSUE TITLE
/ is accepted on decode and isn't escaped as \/ when encoding

### ISSUE THREAD

**Issue by abraxxa** [rurban/Cpanel-JSON-XS#59]
JSON::XS and Cpanel::JSON::XS both accepts `{"key":"1 / 5"}` when decoding and also outputs this when encoding { key => "1 / 5" }.

See http://json.org for the definition of string which lists / ('solidus') as only valid when escaped.

JSON::Tiny is correct in that regard.

**Comment by rurban** [comment]
This escape is purely optional, and we traditionally don't do it anymore.
See e.g. https://stackoverflow.com/questions/4264877/why-is-the-slash-an-escapable-character-in-json

And I cannot repro it in JSON::Tiny:

    perl -MJSON::Tiny=j -e'$h=j q({"key":"1 / 5"}); print %$h'
    => key1 / 5

We had this strange implementation also, but removed it with 0.99:
```
t/07_pc_esc.t:
  $obj = {test => qq|abc/def|};   # / => \/
  $str = $pc->encode($obj);         # but since version 0.99
  is($str,q|{"test":"abc/def"}|); # this handling is deleted.
```

**Comment by abraxxa** [comment]
Thanks for the clarification, we seem to have a validator that is more (incorrectly) strict in that regard and the json.org site isn't very clear on the topic.

**Comment by rurban** [comment]
But I still want to add that optionally, as many argued it is useful in a XML context.

**Comment by rurban** [comment]
Done with the escape_slash option for encode with 2b23cd1cc8b128eb8458045ed23947edc739db46
for GH #47 already

```
perl -MCpanel::JSON::XS -e 'print $j=Cpanel::JSON::XS->new->escape_slash->encode(["1/5"]);'
["1\/5"]
```

**Comment by abraxxa** [comment]
Thanks Reiny!
