### ISSUE TITLE
Reports JSON::PP::Boolean overrides redefined if JSON::PP is loaded later

### ISSUE THREAD

**Issue by charsbar** [rurban/Cpanel-JSON-XS#65]
re: #60  

$ perl -we 'use Cpanel::JSON::XS (); use JSON::PP ()'
Subroutine JSON::PP::Boolean::(0+ redefined at /home/ishigaki/.plenv/versions/5.20.0/lib/perl5/5.20.0/overload.pm line 50.
Subroutine JSON::PP::Boolean::(-- redefined at /home/ishigaki/.plenv/versions/5.20.0/lib/perl5/5.20.0/overload.pm line 50.
Subroutine JSON::PP::Boolean::(++ redefined at /home/ishigaki/.plenv/versions/5.20.0/lib/perl5/5.20.0/overload.pm line 50.

**Comment by rurban** [comment]
Yes, I fixed that in my own variant of JSON::PP already. It's a JSON::PP
problem, I cannot solve. I need to use this namespace for compat.

See
https://github.com/perl11/cperl/commit/baede45414225ca47c0d23d3d515ba153b699c15

and
https://github.com/perl11/cperl/commit/8fdddef0828b6b6118b2b9a61d5ad2d781c3df54

how to avoid the redefine warning.

2016-05-12 14:38 GMT+02:00 Kenichi Ishigaki <notifications@github.com>:

> re: #60 <https://github.com/rurban/Cpanel-JSON-XS/issues/60>
>
> $ perl -we 'use Cpanel::JSON::XS (); use JSON::PP ()'
> Subroutine JSON::PP::Boolean::(0+ redefined at
> /home/ishigaki/.plenv/versions/5.20.0/lib/perl5/5.20.0/overload.pm line
> 50.
> Subroutine JSON::PP::Boolean::(-- redefined at
> /home/ishigaki/.plenv/versions/5.20.0/lib/perl5/5.20.0/overload.pm line
> 50.
> Subroutine JSON::PP::Boolean::(++ redefined at
> /home/ishigaki/.plenv/versions/5.20.0/lib/perl5/5.20.0/overload.pm line
> 50.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rurban/Cpanel-JSON-XS/issues/65>
>



-- 
-- Reini

**Comment by charsbar** [comment]
Thanks for the reply. Confirmed the problem would be fixed by the lazy overloading as Cpanel::JSON::XS does. And naturally, the warnings can be suppressed by preloading JSON::PP explicitly, before some random module uses Cpanel::JSON::XS (directly or indirectly via JSON::MaybeXS), per #60.

However, if we do need to ask makamaka to change JSON::PP, might it be better to ask him to move the guts of JSON::PP::Boolean into lib/JSON/PP/Boolean.pm and use JSON::PP::Boolean from inside of JSON::PP, and set $INC{"JSON/PP/Boolean.pm"} = 1 in Cpanel::JSON::XS, to avoid re-overloading?

**Comment by rurban** [comment]
If he does it right, I will do that, yes. schmorp already decided to ditch that and uses his own class with a different name.

**Comment by charsbar** [comment]
OK. Thanks. I'll talk with him.

**Comment by jzawodn** [comment]
Any updated on this?

**Comment by rurban** [comment]
Yes, see the Types::Bool discussion. I'll wait to see what they decide upon, and will decide later.
Currently they want to hicheck the `bool` namespace which is of course a big nono. So it will need more time.

**Comment by jplindstrom** [comment]
Any update on this?

(If the discussion mentioned above refers to https://github.com/aferreira/cpan-Types-Bool/pull/2 I can't see any resolution there.)

**Comment by rurban** [comment]
No updates yet. See https://github.com/rurban/Cpanel-JSON-XS/issues/65#issuecomment-391645523
hijacking bool is a blocker, so I will not do that.

**Comment by rurban** [comment]
No updates in the broken modules. Not an error here. Closing. If something changes for the better I might be persuaded to do something else, but  it looks nothing better will come out of it. The best is still to use this module and nothing else.

**Comment by charsbar** [comment]
@rurban, the original issue is not resolved yet (not about the new common boolean type distraction, but about lib/JSON/PP/Boolean.pm and %INC). As we discussed about ( https://github.com/rurban/Cpanel-JSON-XS/issues/65#issuecomment-219352754 and https://github.com/rurban/Cpanel-JSON-XS/issues/65#issuecomment-223326159 ),

> > However, if we do need to ask makamaka to change JSON::PP, might it be better to ask him to move the guts of JSON::PP::Boolean into lib/JSON/PP/Boolean.pm and use JSON::PP::Boolean from inside of JSON::PP, and set $INC{"JSON/PP/Boolean.pm"} = 1 in Cpanel::JSON::XS, to avoid re-overloading?

> If he does it right, I will do that, yes. schmorp already decided to ditch that and uses his own class with a different name.

now JSON::PP::Boolean lives in lib/JSON/PP/Boolean.pm (since JSON::PP version 2.92, released on 2017-05-15), and you can tweak %INC. What do you say? Should I send a PR for it, or do we need more discussion about what "does it right" means?
