### ISSUE TITLE
Error message on accidental class method call is a trifle confusing

### ISSUE THREAD

**Issue by shadowcat-mst** [rurban/Cpanel-JSON-XS#66]
sherlock$ perl -MCpanel::JSON::XS -e 'Cpanel::JSON::XS->pretty'
    object is not of type Cpanel::JSON::XS at -e line 1.
    sherlock$ 

While I'm aware that forgetting the ->new-> part was impressively boneheaded on my part, I'd've realised my stupid mistake quicker had the error said "dude, you called an object method on the class, reconsider your life choices". The method name would've been nice too (and Devel::Confess helps me not here).

**Comment by karenetheridge** [comment]
`die 'blessed object required' unless blessed($_[0]);` perhaps?

**Comment by karenetheridge** [comment]
(stupid comment deleted; sorry)

**Comment by rurban** [comment]
This is the standard typemap wording from any wrong OBJECT. e.g. T_PTROBJ in `lib/ExtUtils/typemap`

How about that?
`perl -MCpanel::JSON::XS -e 'Cpanel::JSON::XS->pretty'
string is not of type Cpanel::JSON::XS. You need to create the object with new at -e line 1.`

**Comment by shadowcat-mst** [comment]
On Thu, Jun 02, 2016 at 09:26:06AM -0700, Reini Urban wrote:
> This is the standard typemap wording from any wrong OBJECT. e.g. T_PTROBJ in `lib/ExtUtils/typemap`
> 
> How about that?
> `perl -MCpanel::JSON::XS -e 'Cpanel::JSON::XS->pretty'
> string is not of type Cpanel::JSON::XS. You need to create the object with new at -e line 1.`

Sorry for not replying sooner, got behind on email.

This change is excellent, thank you.

-- 
Matt S Trout - Shadowcat Systems - Perl consulting with a commit bit and a clue

http://shadowcat.co.uk/blog/matt-s-trout/   http://twitter.com/shadowcat_mst/

Email me now on mst (at) shadowcat.co.uk and let's chat about how our CPAN
commercial support, training and consultancy packages could help your team.
