### ISSUE TITLE
3.0218 - crashes/segfaults on Windows + long double (MSWin32-x64-multi-thread-ld)

### ISSUE THREAD

**Issue by kmx** [rurban/Cpanel-JSON-XS#71]
Hi,

when trying to install Cpanel-JSON-XS on 64bit MS Windows perl built with long doubles I see many crashes during make test.

My investigation revealed that the crashing was introduced by this commit: 5624e397cbf0ed1e333510fb7accc734617e13a9 (previous one 8a3da1109bf8ff27e8ec8804ab4c462cf276d6ec is ok)

Here is a perl where you can replicate the problem
http://strawberryperl.com/download/5.24.0.1/strawberry-perl-ld-5.24.0.1-64bit-PDL.zip

--kmx

**Comment by kmx** [comment]
Probably related to http://www.nntp.perl.org/group/perl.perl5.porters/2015/08/msg230472.html

**Comment by rurban** [comment]
Looks like we need to probe for a broken modfl

**Comment by rurban** [comment]
patched with 3.0219
