### ISSUE TITLE
CLONE broken in latest version (3.0226)

### ISSUE THREAD

**Issue by y** [rurban/Cpanel-JSON-XS#80]
After upgrading to 3.0226 the following code no longer works:

    #!/usr/bin/env perl
    use forks;
    use 5.010;
    use strict;
    use warnings;

    use JSON::MaybeXS;

    my $thread = threads->new( sub {
        say encode_json({a => 1, b => 2});
    } );
    $thread->join;

It produces the following error:

    Usage: Cpanel::JSON::XS::CLONE() at /tmp/perlbrew/perls/perl-5.24/lib/site_perl/5.24.1/darwin-thread-multi-2level/forks.pm line 3746.

Downgrading back to 3.0225, it works as expected:

    {"b":2,"a":1}

perl -V

    Summary of my perl5 (revision 5 version 24 subversion 1) configuration:
    
    Platform:
        osname=darwin, osvers=15.6.0, archname=darwin-thread-multi-2level
        uname='darwin mac.sw 15.6.0 darwin kernel version 15.6.0: wed nov 2 20:30:56 pdt 2016; root:xnu-3248.60.11.1.2~2release_x86_64 x86_64 '
        config_args='-de -Dprefix=/Users/y/sw/perlbrew/perls/perl-5.24 -Dusethreads -Aeval:scriptdir=/Users/y/sw/perlbrew/perls/perl-5.24/bin'
        hint=recommended, useposix=true, d_sigaction=define
        useithreads=define, usemultiplicity=define
        use64bitint=define, use64bitall=define, uselongdouble=undef
        usemymalloc=n, bincompat5005=undef
    Compiler:
        cc='cc', ccflags ='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/sw/include -I/opt/sw/include',
        optimize='-O3',
        cppflags='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/sw/include -I/opt/sw/include'
        ccversion='', gccversion='4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)', gccosandvers=''
        intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
        d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
        ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
        alignbytes=8, prototype=define
    Linker and Libraries:
        ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -fstack-protector-strong -L/usr/sw/lib -L/opt/sw/lib'
        libpth=/usr/sw/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib /opt/sw/lib
        libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
        perllibs=-lpthread -ldl -lm -lutil -lc
        libc=, so=dylib, useshrplib=false, libperl=libperl.a
        gnulibc_version=''
    Dynamic Linking:
        dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
        cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -L/usr/sw/lib -L/opt/sw/lib -fstack-protector-strong'

    Characteristics of this binary (from libperl): 
    Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                            PERL_COPY_ON_WRITE PERL_DONT_CREATE_GVSV
                            PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                            PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP
                            PERL_PRESERVE_IVUV USE_64_BIT_ALL USE_64_BIT_INT
                            USE_ITHREADS USE_LARGE_FILES USE_swE
                            USE_swE_COLLATE USE_swE_CTYPE
                            USE_swE_NUMERIC USE_swE_TIME USE_PERLIO
                            USE_PERL_ATOF USE_REENTRANT_API
    Built under darwin
    Compiled at Jan 14 2017 20:22:44
    %ENV:
        PERL5LIB=""
        PERLBREW_BASHRC_VERSION="0.78"
        PERLBREW_HOME="/Users/y/.perlbrew"
        PERLBREW_MANPATH="/Users/y/sw/perlbrew/perls/perl-5.24/man"
        PERLBREW_PATH="/Users/y/sw/perlbrew/bin:/Users/y/sw/perlbrew/perls/perl-5.24/bin"
        PERLBREW_PERL="perl-5.24"
        PERLBREW_ROOT="/Users/y/sw/perlbrew"
        PERLBREW_VERSION="0.78"
        PERL_CPANM_OPT="-q"
    @INC:
        /Users/y/sw/perl5
        /Users/y/sw/perlbrew/perls/perl-5.24/lib/site_perl/5.24.1/darwin-thread-multi-2level
        /Users/y/sw/perlbrew/perls/perl-5.24/lib/site_perl/5.24.1
        /Users/y/sw/perlbrew/perls/perl-5.24/lib/5.24.1/darwin-thread-multi-2level
        /Users/y/sw/perlbrew/perls/perl-5.24/lib/5.24.1
        /Users/y/sw/perlbrew/perls/perl-5.24/lib/site_perl
        .

**Comment by rurban** [comment]
This cannot be the reason. 3.0226 only relaxed the test `t/11_pc_expo.t`
https://github.com/rurban/Cpanel-JSON-XS/commit/e35bb02f4fc91438ebd87be2897b074bd188d851
which could not have changed CLONE behavior in any way. Investigating...
