### ISSUE TITLE
double encoded UTF8 string

### ISSUE THREAD

**Issue by amlan-sw** [rurban/Cpanel-JSON-XS#86]
dear owner/maintainer 

Cpanel::JSON::XS version: 3.0233
Perl 5.16 CentOS 7

this oneliner:

bash# perl -e 'use Cpanel::JSON::XS(); $a = {a=>"JSON::XS - 正しくて高速な JSON シリアライザ/デシリアライザ"}; print &Cpanel::JSON::XS::encode_json($a)'

have result double encoded UTF8 :

{"a":"JSON::XS - æ­£ã��ã��ã�¦é«�é��ã�ª JSON ã�·ã�ªã�¢ã�©ã�¤ã�¶/ã��ã�·ã�ªã�¢ã�©ã�¤ã�¶"}

I try to patch XS.xs with some C code from:

https://stackoverflow.com/questions/1031645/how-to-detect-utf-8-in-plain-c
answer no. 2

//-------------------------------------------------
char already_utf8(const char * string)
{
    const unsigned char * bytes = (const unsigned char *)string;
    if(!string)
        return 0;

    while(*bytes)
    {
        if( (// ASCII
             // use bytes[0] <= 0x7F to allow ASCII control characters
                bytes[0] == 0x09 ||
                bytes[0] == 0x0A ||
                bytes[0] == 0x0D ||
                (0x20 <= bytes[0] && bytes[0] <= 0x7E)
            )
        ) {
            bytes += 1;
            continue;
        }

        if( (// non-overlong 2-byte
                (0xC2 <= bytes[0] && bytes[0] <= 0xDF) &&
                (0x80 <= bytes[1] && bytes[1] <= 0xBF)
            )
        ) {
            bytes += 2;
            continue;
        }

        if( (// excluding overlongs
                bytes[0] == 0xE0 &&
                (0xA0 <= bytes[1] && bytes[1] <= 0xBF) &&
                (0x80 <= bytes[2] && bytes[2] <= 0xBF)
            ) ||
            (// straight 3-byte
                ((0xE1 <= bytes[0] && bytes[0] <= 0xEC) ||
                    bytes[0] == 0xEE ||
                    bytes[0] == 0xEF) &&
                (0x80 <= bytes[1] && bytes[1] <= 0xBF) &&
                (0x80 <= bytes[2] && bytes[2] <= 0xBF)
            ) ||
            (// excluding surrogates
                bytes[0] == 0xED &&
                (0x80 <= bytes[1] && bytes[1] <= 0x9F) &&
                (0x80 <= bytes[2] && bytes[2] <= 0xBF)
            )
        ) {
            bytes += 3;
            continue;
        }

        if( (// planes 1-3
                bytes[0] == 0xF0 &&
                (0x90 <= bytes[1] && bytes[1] <= 0xBF) &&
                (0x80 <= bytes[2] && bytes[2] <= 0xBF) &&
                (0x80 <= bytes[3] && bytes[3] <= 0xBF)
            ) ||
            (// planes 4-15
                (0xF1 <= bytes[0] && bytes[0] <= 0xF3) &&
                (0x80 <= bytes[1] && bytes[1] <= 0xBF) &&
                (0x80 <= bytes[2] && bytes[2] <= 0xBF) &&
                (0x80 <= bytes[3] && bytes[3] <= 0xBF)
            ) ||
            (// plane 16
                bytes[0] == 0xF4 &&
                (0x80 <= bytes[1] && bytes[1] <= 0x8F) &&
                (0x80 <= bytes[2] && bytes[2] <= 0xBF) &&
                (0x80 <= bytes[3] && bytes[3] <= 0xBF)
            )
        ) {
            bytes += 4;
            continue;
        }

        return 0;
    }

    return 1;
}
//-------------------------------------------------

then at XS.xs function encode_sv line 1576

I change:

     encode_str (enc, str, len, SvUTF8 (sv));

to

     encode_str (aTHX_ enc, str, len, already_utf8(str) ? 1 : SvUTF8 (sv));

then try again:

bash# perl -e 'use Cpanel::JSON::XS(); $a = {a=>"JSON::XS - 正しくて高速な JSON シリアライザ/デシリアライザ"}; print &Cpanel::JSON::XS::encode_json($a)'

result:

{"a":"JSON::XS - 正しくて高速な JSON シリアライザ/デシリアライザ"}

please apply or fix in next release.
patched source code attached 
[XS.xs.txt](https://github.com/rurban/Cpanel-JSON-XS/files/1095466/XS.xs.txt)

sorry for my bad english,
thx,
asw

**Comment by rurban** [comment]
Sorry, but the correct fix is to mark the string as utf8, otherwise it's just bytes.

$ perl -e 'use utf8; use Cpanel::JSON::XS(); $a = {a=>"JSON::XS - 正しくて高速な JSON シリアライザ/ デシリアライザ"}; print &Cpanel::JSON::XS::encode_json($a)'

{"a":"JSON::XS - 正しくて高速な JSON シリアライザ/デシリアライザ"}

See the **use utf8**

**Comment by Grinnz** [comment]
Also note that if your input is coming from somewhere else and not the source code like in this example, you need to decode that input properly before passing it on to a JSON encoder as well.
