### ISSUE TITLE
Allow list context?

### ISSUE THREAD

**Issue by rurban** [rurban/Cpanel-JSON-XS#90]
See https://www.snellman.net/blog/archive/2017-07-18-wantarray/
for an interesting bug with JSON::PP failing to decode a File::Slurp file on windows, as
JSON::XS (and this fork) apply scalar context to the arg, i.e. slurping all the lines into one huge string, and not a list of lines. The problem was with JSON::PP in list context and a wrong line split.
 
```
cv = newXSproto_portable("Cpanel::JSON::XS::decode_json", XS_Cpanel__JSON__XS_decode_json, file, "$;$");
```

A change would be to disable `PROTOTYPES: ENABLE` for the encoder and decoder functions, and allow decode of array strings, not just a scalar.
JSON::PP does so.
But this does not help with performance, only reading directly from an IO handle would help.

Note: OP's underlying problem was not with JSON::XS but with JSON::PP using said list context of 
File::Slurp, reading a file line by line, which failed on *wrong* line-endings: CRLF on linux split into CRLF. A JSON::PP bug with wrong white-space strictness.

**Comment by rurban** [comment]
Rather allow IO handles

**Comment by Grinnz** [comment]
I consider this a bug in the File::Slurp interface. File::Slurper provides separate read_text and read_lines functions that are not context sensitive.

**Comment by rurban** [comment]
Well, I'm quite okay with the wantarray feature and File::Slurp using it.
The problem is after that, in the list context of JSON::PP.
