### ISSUE TITLE
Cpanel::JSON::XS changes locale for all process threads with race condition

### ISSUE THREAD

**Issue by pali** [rurban/Cpanel-JSON-XS#99]
Commit which introduced this problem: https://github.com/rurban/Cpanel-JSON-XS/commit/f799b2e83bd38a3f6d3fba57ea3177261cd48b97

Basically if perl interpreter is running only in one thread (e.g. in multithread application which uses one thread for perl), then Cpanel::JSON::XS changes locale temporary for all running threads, not just for that one in which is running perl. 

Fix should be straightforward, using function `uselocale` which affects only one thread, instead of `setlocale` which affects all threads of process.

**Comment by rurban** [comment]
Right, thanks

**Comment by rurban** [comment]
NEED_NUMERIC_LOCALE_C is only defined for <5.22.
I_XLOCALE is only defined since 5.25.4, HAS_USELOCALE since 5.24.
So we'd need to probe for xlocale.h and HAS_USELOCALE by ourselves on those old perls.

**Comment by rurban** [comment]
BTW: Not even perl 5.26 uses the thread-safe `uselocale` for numbers, just `do_setlocale_c`, which is global. Only in my_strerror and my_nl_langinfo uselocale is used.

**Comment by pali** [comment]
https://github.com/rurban/Cpanel-JSON-XS/commit/9f82ddfe178970eddc215c621e92edb9db9cc11e#r27234280

**Comment by rurban** [comment]
I added probes and call uselocale only with threaded perls.
Should we use the thread-safe code even with unthreaded perls?
Only if our perl might be called with a child. But this might race with the global
process locale all times, because perl_init sets the locale already.
